/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasAsegurado;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marvin
 */
public class Pagos extends javax.swing.JFrame {

    String dpi;
    DefaultTableModel modelo;
    int correlativo = 1;
    /**
     * Creates new form Pagos
     */
    public Pagos() {
        initComponents();
    }
    public Pagos(String dpi) {
        this.dpi=dpi;
        initComponents();
    }
    
    public void mostrar(){
        this.show(true);
        llenaTextArea();
        mostrarDatos();
    }
    
    public void llenaTextArea() {

        String aux = "";
        //Se obtienen los datos del usuario
        for (int conteo = 0; conteo < Main.Main.asegurados.length; conteo++) {
            if (Main.Main.asegurados[conteo] != null) {
                if (this.dpi.equals(Main.Main.asegurados[conteo].getDpi())) {
                    aux = "NOMBRE: " + Main.Main.asegurados[conteo].getNombres() + " " + Main.Main.asegurados[conteo].getApellidos() + "\n"
                            + "TELEFONO: " + Main.Main.asegurados[conteo].getTelefono() + "\n"
                            + "DPI: " + Main.Main.asegurados[conteo].getDpi();
                    break;
                }
            }
        }
        jTextArea1.setText(aux);
    }
    
    private void mostrarDatos() {
        modelo = new DefaultTableModel();
        modelo.addColumn("CORRELATIVO");
        modelo.addColumn("TIPO");
        modelo.addColumn("TOTAL");
        modelo.addColumn("FECHA INICIO");
        modelo.addColumn("FECHA FIN");
        modelo.addColumn("CODIGO");
        this.jTable1.setModel(modelo);
        this.jTable1.setDefaultEditor(Object.class, null);

        String info[] = new String[6];
        System.out.println(this.dpi);
        for (int conteo = 0; conteo < Main.Main.pagos.length; conteo++) {
            if (Main.Main.pagos[conteo] != null) {
                if (this.dpi.equals(Main.Main.pagos[conteo].getDpi())) {
                    info[0] = Integer.toString(this.correlativo);
                    this.correlativo++;
                    info[1] = Main.Main.pagos[conteo].getPoliza();
                    info[2] = String.valueOf(Main.Main.pagos[conteo].getTotal());
                    info[3] = Main.Main.pagos[conteo].getFechaInicio();
                    info[4] = Main.Main.pagos[conteo].getFechaFin();
                    info[5] = Integer.toString(Main.Main.pagos[conteo].getCodigo());

                    modelo.addRow(info);
                }                          
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAGOS");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CORRELATIVO", "TIPO", "TOTAL", "FECHA INICIO", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
