/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasPrincipal;

import Objetos.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Marvin
 */
public class CargarDatos extends javax.swing.JFrame {

    /**
     * Creates new form Principal_CargaDatos
     */
    public CargarDatos() {
        initComponents();
        //this.jTextField1.setL
    }

    public void mostrar() {
        this.show(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CARGA DE DATOS");
        setPreferredSize(new java.awt.Dimension(538, 333));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Cargar datos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String aux;
        boolean ingresado = false;
        aux = jTextArea1.getText();
        String arregloAux[] = aux.split("\n", 0);
        if (aux.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar datos");
        }
        for (int i = 0; i < arregloAux.length; i++) {
            if (arregloAux[i].equals("")) {

            } else {
                String arregloDatosAux[] = arregloAux[i].split(",", 0);
                if (arregloDatosAux[0].equals("TIPO") || arregloDatosAux[0].equals("MODELO")
                        || arregloDatosAux[0].equals("MARCA") || arregloDatosAux[0].equals("LINEA")
                        || arregloDatosAux[0].equals("USO") || arregloDatosAux[0].equals("MECANICA")
                        || arregloDatosAux[0].equals("REPUESTO")) {
                    switch (arregloDatosAux[0]) {
                        case "TIPO":
                            agregaTipo(arregloDatosAux);
                            ingresado = true;
                            break;
                        case "MODELO":
                            agregaModelo(arregloDatosAux);
                            ingresado = true;
                            break;
                        case "MARCA":
                            agregaMarca(arregloDatosAux);
                            ingresado=true;
                            break;
                        case "LINEA":
                            agregaLinea(arregloDatosAux);
                            ingresado=true;
                            break;
                        case "USO":
                            agregaUso(arregloDatosAux);
                            ingresado=true;
                            break;
                        case "MECANICA":
                            agregaMecanica(arregloDatosAux);
                            ingresado=true;
                            break;
                        case "REPUESTO":
                            agregaRepuesto(arregloDatosAux);
                            ingresado=true;
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Alguno de los datos se ingresaron incorrectamente, no podra agregarse");
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El dato Numero " + (i + 1) + " se ingreso incorrectamente, no podra agregarse");
                }
            }
        }
        jTextArea1.setText("");
        if (ingresado) {
            JOptionPane.showMessageDialog(null, "DATOS AGREGADOS CON EXITO");
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregaTipo(String datos[]) {

        for (int conteo = 0; conteo < 50; conteo++) {
            if (Main.Main.tipos[conteo] == null) {
                Main.Main.tipos[conteo] = new Tipo(datos[1], Integer.parseInt(datos[2]));
                System.out.println("se agrego tipo");
                break;
            }
        }
    }

    private void agregaModelo(String datos[]) {
        for (int conteo = 0; conteo < Main.Main.modelos.length; conteo++) {
            if (Main.Main.modelos[conteo] == null) {
                Main.Main.modelos[conteo] = new Modelo(datos[1], Double.parseDouble(datos[2]));
                System.out.println("se agrego modelo");
                break;
            }
        }
    }

    private void agregaMarca(String datos[]) {
        for (int conteo = 0; conteo < Main.Main.marcas.length; conteo++) {
            if (Main.Main.marcas[conteo] == null) {
                Main.Main.marcas[conteo] = new Marca(datos[1], Double.parseDouble(datos[2]));
                System.out.println("se agrego marca "+Main.Main.marcas[conteo].getNombre());
                break;
            }
        }
    }

    private void agregaLinea(String datos[]) {
        for (int conteo = 0; conteo < Main.Main.lineas.length; conteo++) {
            if (Main.Main.lineas[conteo] == null) {
                Main.Main.lineas[conteo] = new Linea(datos[1], Double.parseDouble(datos[2]));
                System.out.println("se agrego linea");
                break;
            }
        }
    }

    private void agregaUso(String datos[]) {
        for (int conteo = 0; conteo < Main.Main.usos.length; conteo++) {
            if (Main.Main.usos[conteo] == null) {
                Main.Main.usos[conteo] = new Uso(datos[1], Double.parseDouble(datos[2]));
                System.out.println("se agrego uso");
                break;
            }
        }
    }

    private void agregaMecanica(String datos[]) {
        for (int conteo = 0; conteo < Main.Main.mecanicas.length; conteo++) {
            if (Main.Main.mecanicas[conteo] == null) {
                Main.Main.mecanicas[conteo] = new Mecanica(datos[1], Integer.parseInt(datos[2]));
                System.out.println("se agrego mecanica");
                break;
            }
        }
    }

    private void agregaRepuesto(String datos[]) {
        for (int conteo = 0; conteo < Main.Main.repuestos.length; conteo++) {
            if (Main.Main.repuestos[conteo] == null) {
                Main.Main.repuestos[conteo] = new Repuesto(datos[1], Double.parseDouble(datos[2]));
                System.out.println("se agrego repuesto");
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
