/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasAdmin;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.*;

/**
 *
 * @author Marvin
 */
public class SolicitudesSeguro extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form SolicitudesSeguro
     */
    public SolicitudesSeguro() {
        initComponents();
        mostrarDatos();
    }

    private void mostrarDatos() {
        modelo = new DefaultTableModel();
        modelo.addColumn("DPI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("TIPO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("MONTO");
        modelo.addColumn("POLIZA");
        modelo.addColumn("DEDUCIBLE");
        this.jTable1.setModel(modelo);
        this.jTable1.setDefaultEditor(Object.class, null);
        String info[];
        info = new String[8];
//        DecimalFormat formato1 = new DecimalFormat("#.00");
//            jTextField5.setText(String.valueOf(formato1.format(costoPrima)));
        DecimalFormat formato1 = new DecimalFormat("#.00");
        for (int conteo = 0; conteo < Main.Main.solicitantes.length; conteo++) {
            if (Main.Main.solicitantes[conteo] != null) {
                    info[0] = Main.Main.solicitantes[conteo].getDpi();
                    System.out.println(info[0]);
                    info[1] = Main.Main.solicitantes[conteo].getNombres();
                    info[2] = Main.Main.solicitantes[conteo].getTelefono();
                    info[3] = Main.Main.solicitantes[conteo].getTipo();
                    info[4] = Main.Main.solicitantes[conteo].getTipoVehiculo() + ", "
                            + Main.Main.solicitantes[conteo].getModeloVehiculo() + ", "
                            + Main.Main.solicitantes[conteo].getMarcaVehiculo() + ", "
                            + Main.Main.solicitantes[conteo].getLineaVehiculo();
                    info[5] = Integer.toString(Main.Main.solicitantes[conteo].getValorVehiculo());
                    info[6] = String.valueOf(formato1.format(Main.Main.solicitantes[conteo].getCostoPrima()));
                    info[7] = String.valueOf(formato1.format(Main.Main.solicitantes[conteo].getDeducible()));

                    modelo.addRow(info);               
            }
        }
    }

    public void mostrar() {
        this.show(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SOLICITUDES DE SEGURO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DPI", "NOMBRE", "TELEFONO", "TIPO", "DESCRIPCION", "MONTO", "POLIZA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("APROBAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RECHAZAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String nombre;
        String apellido;
        String dpi;
        String telefono;
        String tipoVehiculo;
        String marca;
        String linea;
        String modelo;
        int valorVehiculo;
        double costoPrima;
        double deducible;

        System.out.println(fila);

        nombre = Main.Main.solicitantes[fila].getNombres();
        apellido = Main.Main.solicitantes[fila].getApellidos();
        dpi = Main.Main.solicitantes[fila].getDpi();
        telefono = Main.Main.solicitantes[fila].getTelefono();
        tipoVehiculo = Main.Main.solicitantes[fila].getTipoVehiculo();
        marca = Main.Main.solicitantes[fila].getMarcaVehiculo();
        linea = Main.Main.solicitantes[fila].getLineaVehiculo();
        modelo = Main.Main.solicitantes[fila].getModeloVehiculo();
        valorVehiculo = Main.Main.solicitantes[fila].getValorVehiculo();
        costoPrima = Main.Main.solicitantes[fila].getCostoPrima();
        deducible = Main.Main.solicitantes[fila].getDeducible();

        for (int conteo = 0; conteo < Main.Main.asegurados.length; conteo++) {
            if (Main.Main.asegurados[conteo] == null) {
                Objetos.Asegurado asegurado = new Objetos.Asegurado(nombre, apellido, dpi, telefono, tipoVehiculo, marca, linea, modelo, valorVehiculo, costoPrima, deducible);
                Main.Main.asegurados[conteo] = asegurado;
                Main.Main.solicitantes[conteo].setStatus("ACEPTADO");
                System.out.println("agregado");
                break;
            }
        }
        JOptionPane.showMessageDialog(null, "Se ha agregado el usuario");
        mostrarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        Main.Main.solicitantes[fila].setStatus("RECHAZADO");
        JOptionPane.showMessageDialog(null, "El solicitante ha sido rechazado con exito");

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudesSeguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitudesSeguro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
