/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasNoAsegurado;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Objetos.*;

/**
 *
 * @author Marvin
 */
public class MisIncidentes extends javax.swing.JFrame {

    DefaultTableModel modelo;
    String dpi;

    /**
     * Creates new form MisIncidentes
     */
    public MisIncidentes() {
        initComponents();
    }

    public MisIncidentes(String dpi) {
        this.dpi = dpi;
        modelo = new DefaultTableModel();
        initComponents();
    }

    public void mostrar() {
        this.show(true);
        mostrarDatos();
        llenaTextArea();
    }

    public void llenaTextArea() {

        String aux = "";
        //Se obtienen los datos del usuario
        for (int conteo = 0; conteo < Main.Main.noAsegurados.length; conteo++) {
            if (Main.Main.noAsegurados[conteo] != null) {
                if (this.dpi.equals(Main.Main.noAsegurados[conteo].getDpi())) {
                    aux = "NOMBRE: " + Main.Main.noAsegurados[conteo].getNombres() + " " + Main.Main.noAsegurados[conteo].getApellidos() + "\n"
                            + "TELEFONO: " + Main.Main.noAsegurados[conteo].getTelefono() + "\n"
                            + "DPI: " + Main.Main.noAsegurados[conteo].getDpi();
                    break;
                }
            }
        }
        jTextArea1.setText(aux);
    }

    private void mostrarDatos() {
        modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("ROL");
        modelo.addColumn("COSTO REAL");
        modelo.addColumn("PAGO REQUERIDO");
        modelo.addColumn("ESTADO");
        modelo.addColumn("PAGO");
        this.jTable1.setModel(modelo);
        this.jTable1.setDefaultEditor(Object.class, null);

        String info[] = new String[6];
        for (int conteo = 0; conteo < Main.Main.incidentes.length; conteo++) {
            if (Main.Main.incidentes[conteo] != null) {
                if (this.dpi.equals(Main.Main.incidentes[conteo].getDpiTercero())) {
                    info[0] = Integer.toString(Main.Main.incidentes[conteo].getCodigo());
                    info[1] = Main.Main.incidentes[conteo].getRolTercero();
                    info[2] = String.valueOf(Main.Main.incidentes[conteo].getCostoReal());
                    info[3] = String.valueOf(Main.Main.incidentes[conteo].getPagoRequeridoTercero());
                    info[4] = Main.Main.incidentes[conteo].getEstado();
                    info[5] = Main.Main.incidentes[conteo].getPago();

                    modelo.addRow(info);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MIS INCIDENTES");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "ROL", "COSTO REAL", "PAGO REQUERIDO", "ESTADO", "PAGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("DETALLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PAGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String dato = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 0));
        System.out.println(dato);
        
        int codigo = (int) (Math.random() * 10000) + 1;

       
        for (int contador = 0; contador < Main.Main.incidentes.length; contador++) {
            if (Main.Main.incidentes[contador] != null) {
                if (dato.equals(Integer.toString(Main.Main.incidentes[contador].getCodigo()))) {
                    if (Main.Main.incidentes[contador].isAseguradoCulpable()) {
                        JOptionPane.showMessageDialog(null, "Su saldo es cero, no puede pagar.");
                    }else{
                        Main.Main.incidentes[contador].setPago("PAGADO");
                        for (int correlativo = 0; correlativo < Main.Main.pagos.length; correlativo++) {
                            if (Main.Main.pagos[correlativo]==null) {
                                //crea nuevo pago
                                Main.Main.pagos[correlativo]=new Pago(this.dpi,"INCIDENTE AUTO",Main.Main.incidentes[contador].getPagoRequeridoTercero(),
                                Integer.toString(Main.Main.fecha.getDia())+"/"+Integer.toString(Main.Main.fecha.getMes())+"/"+
                                        Integer.toString(Main.Main.fecha.getAnio()),Integer.toString(Main.Main.fecha.getDia())+"/"+Integer.toString(Main.Main.fecha.getMes())+"/"+
                                        Integer.toString(Main.Main.fecha.getAnio()),codigo);
                                break;
                            }
                        }
                        JOptionPane.showMessageDialog(null, "PAGO REALIZADO CON EXITO");
                    break;
                    }
                }
            }
        }
        mostrarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dato = String.valueOf(modelo.getValueAt(jTable1.getSelectedRow(), 0));

        String[][] detalleAux = new String[50][3];
        String aux = "";

        //se recorre banco de incidentes y ses obtiene el detalle segun su codigo de incidente
        for (int contador = 0; contador < Main.Main.incidentes.length; contador++) {
            if (Main.Main.incidentes[contador] != null) {
                if (dato.equals(Integer.toString(Main.Main.incidentes[contador].getCodigo()))) {
                    for (int fila = 0; fila < 50; fila++) {
                        for (int columna = 0; columna < 3; columna++) {
                            if (Main.Main.incidentes[contador] != null) {
                                detalleAux[fila][columna] = Main.Main.incidentes[contador].getDetalle()[fila][columna];
                            }
                        }
                    }
                    break;
                }
            }
        }
        //se genera string usando el detalle obtenido
        for (int fila = 0; fila < 50; fila++) {
            if (detalleAux[fila][0]!=null) {
                for (int columna = 0; columna < 3; columna++) {
                aux = aux + detalleAux[fila][columna] + " ";
            }
            aux = aux + "\n";
            }else{
                break;
            }           
        }
        //se imprime string geneado
        JOptionPane.showMessageDialog(null, aux);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisIncidentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisIncidentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
